version: '3'

services:

    db:
        image: mysql:8
        env_file: vars.env
        container_name: db
        restart: always
        volumes:
            - ./sql-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        #expose:
        #    - 3306
        networks:
            - twatter-back


    twatter-server:
        restart: always
        depends_on: 
            - db
        env_file: vars.env
        container_name: twatter-server
        build: ./server
        image: twatter-server
        ports:
            - 3000:3000
        networks:
            - twatter-back
        volumes:
            - ./server:/twatter-server

networks:
    twatter-back:
        name: twatter-back
        driver: bridge
    
